DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS CUSTOMER_TYPE_DISCOUNT;
DROP TABLE IF EXISTS T_COUNTRY;
DROP TABLE IF EXISTS T_COUNTRY_AREA;
DROP TABLE IF EXISTS T_PATIENT_DETAILS;

CREATE TABLE USERS (
  USER_ID varchar(20) NOT NULL,
  PASSWORD varchar(30) NOT NULL,
  CUS_TYPE varchar(30) NOT NULL
  );

CREATE TABLE CUSTOMER_TYPE_DISCOUNT(
CUS_TYPE varchar(30) NOT NULL,
MIN_VALUE double NOT NULL,
MAX_VALUE double ,
DISCOUNT_PRC INTEGER DEFAULT 0);


CREATE TABLE T_COUNTRY(
COUNTRY_ID INT NOT NULL,
COUNTRY_NAME  varchar(30) NOT NULL,
IS_ACTIVE INT NOT NULL DEFAULT 1 );

CREATE TABLE T_COUNTRY_AREA(
AREA_ID INT NOT NULL,
AREA_NAME  varchar(30) NOT NULL,
COUNTRY_ID INT NOT NULL,
IS_ACTIVE INT NOT NULL DEFAULT 1 );


CREATE TABLE T_PATIENT_DETAILS(
PATIENT_ID LONG IDENTITY PRIMARY KEY,
PATIENT_NAME  varchar(30) NOT NULL,
COUNTRY_ID INT NOT NULL,
AREA_ID INT NOT NULL,
PATIENT_STATUS INT NOT NULL,
CREATE_DATE DATE  NOT NULL DEFAULT CURRENT_DATE,
UPDATE_DATE DATE,
REMARKS varchar(500),
IS_ACTIVE INT NOT NULL DEFAULT 1 );





