DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS CUSTOMER_TYPE_DISCOUNT;


CREATE TABLE USERS (
  USER_ID varchar(20) NOT NULL,
  PASSWORD varchar(30) NOT NULL,
  CUS_TYPE varchar(30) NOT NULL
  );

CREATE TABLE CUSTOMER_TYPE_DISCOUNT(
CUS_TYPE varchar(30) NOT NULL,
MIN_VALUE double NOT NULL,
MAX_VALUE double ,
DISCOUNT_PRC INTEGER DEFAULT 0);